export const GAMEVARS = {
    players: [],
    tempPlayers: [],
    deadPlayers: [],
    playersGroup: [],
    playerSkins: [],
    platforms: [],
    jumppads: [],
    belts: [],
    cursors: "",
    bombs: {},
    playerSpeed: 200,
    speedLimit: 2000,
    knockback: 70,
    maxHealth: 10,
    cooldown: 20,
    jumpSpeed: 530,
    fireTimer: [0,0,0,0],
    playerHealth: [],
    deadPlayerCount: 0,
    shakeAmount: .01,
    shakeDuration: 100
}